# Generated by Django 4.2 on 2023-05-21 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food and groceries', 'Food and groceries'), ('Salary', 'Salary'), ('Bills', 'Bills'), ('Shopping', 'Shopping'), ('Investment', 'Investment'), ('Travel', 'Travel'), ('Others', 'Others')], default='Food and groceries', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], default='Expense', max_length=10),
        ),
    ]
