# Generated by Django 4.2 on 2023-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_category_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food and groceries', 'Food and groceries 🍕'), ('Salary', 'Salary 💰'), ('Bills', 'Bills 🔌'), ('Shopping', 'Shopping 🛍️'), ('Investment', 'Investment 💸'), ('Travel', 'Travel ✈️'), ('Others', 'Others 💅')], default='Food and groceries', max_length=20),
        ),
    ]
